// This file is auto-generated by Flughafen
// Do not edit manually - regenerate using `flughafen generate-types`

// Ambient module declaration - types are automatically available
// No need to import this file explicitly
