// This file is auto-generated by Flughafen
// Do not edit manually - regenerate using `flughafen generate-types`

// Ambient module declaration - types are automatically available
// No need to import this file explicitly

/**
 * Inputs for actions/checkout@v4
 * Checkout a Git repository at a particular version
 */
export interface ActionsCheckoutV4Inputs {
  /**
   * Repository name with owner. For example, actions/checkout
   * @default "${{ github.repository }}"
   */
  repository?: string;

  /**
   * The branch, tag or SHA to checkout. When checking out the repository
   * that triggered a workflow, this defaults to the reference or SHA for
   * that event.  Otherwise, uses the default branch.

   */
  ref?: string;

  /**
   * Personal access token (PAT) used to fetch the repository. The PAT is
   * configured with the local git config, which enables your scripts to
   * run authenticated git commands. The post-job step removes the PAT.

We
   * recommend using a service account with the least permissions
   * necessary. Also when generating a new PAT, select the least scopes
   * necessary.

[Learn more about creating and using encrypted
   * secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

   * @default "${{ github.token }}"
   */
  token?: string;

  /**
   * SSH key used to fetch the repository. The SSH key is configured with
   * the local git config, which enables your scripts to run authenticated
   * git commands. The post-job step removes the SSH key.

We recommend
   * using a service account with the least permissions necessary.

[Learn
   * more about creating and using encrypted
   * secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

   */
  'ssh-key'?: string;

  /**
   * Known hosts in addition to the user and global host key database. The
   * public SSH keys for a host may be obtained using the utility
   * `ssh-keyscan`. For example, `ssh-keyscan github.com`. The public key
   * for github.com is always implicitly added.

   */
  'ssh-known-hosts'?: string;

  /**
   * Whether to perform strict host key checking. When true, adds the
   * options `StrictHostKeyChecking=yes` and `CheckHostIP=no` to the SSH
   * command line. Use the input `ssh-known-hosts` to configure additional
   * hosts.

   * @default true
   */
  'ssh-strict'?: boolean;

  /**
   * The user to use when connecting to the remote SSH host. By default
   * 'git' is used.

   * @default "git"
   */
  'ssh-user'?: string;

  /**
   * Whether to configure the token or SSH key with the local git config
   * @default true
   */
  'persist-credentials'?: boolean;

  /**
   * Relative path under $GITHUB_WORKSPACE to place the repository
   */
  path?: string;

  /**
   * Whether to execute `git clean -ffdx && git reset --hard HEAD` before
   * fetching
   * @default true
   */
  clean?: boolean;

  /**
   * Partially clone against a given filter. Overrides sparse-checkout if
   * set.

   * @default null
   */
  filter?: string;

  /**
   * Do a sparse checkout on given patterns. Each pattern should be
   * separated with new lines.

   * @default null
   */
  'sparse-checkout'?: string;

  /**
   * Specifies whether to use cone-mode when doing a sparse checkout.

   * @default true
   */
  'sparse-checkout-cone-mode'?: boolean;

  /**
   * Number of commits to fetch. 0 indicates all history for all branches
   * and tags.
   * @default 1
   */
  'fetch-depth'?: number;

  /**
   * Whether to fetch tags, even if fetch-depth > 0.
   * @default false
   */
  'fetch-tags'?: boolean;

  /**
   * Whether to show progress status output when fetching.
   * @default true
   */
  'show-progress'?: boolean;

  /**
   * Whether to download Git-LFS files
   * @default false
   */
  lfs?: boolean;

  /**
   * Whether to checkout submodules: `true` to checkout submodules or
   * `recursive` to recursively checkout submodules.

When the `ssh-key`
   * input is not provided, SSH URLs beginning with `git@github.com:` are
   * converted to HTTPS.

   * @default false
   */
  submodules?: boolean;

  /**
   * Add repository path as safe.directory for Git global config by running
   * `git config --global --add safe.directory <path>`
   * @default true
   */
  'set-safe-directory'?: boolean;

  /**
   * The base URL for the GitHub instance that you are trying to clone
   * from, will use environment defaults to fetch from the same instance
   * that the workflow is running from unless specified. Example URLs are
   * https://github.com or https://my-ghes-server.example.com
   */
  'github-server-url'?: string;
}

/**
 * Inputs for actions/setup-node@v4
 * Setup a Node.js environment by adding problem matchers and optionally downloading and adding it to the PATH.
 */
export interface ActionsSetupNodeV4Inputs {
  /**
   * Set always-auth in npmrc.
   * @default "false"
   */
  'always-auth'?: string;

  /**
   * Version Spec of the version to use. Examples: 12.x, 10.15.1,
   * >=10.15.0.
   */
  'node-version'?: string;

  /**
   * File containing the version Spec of the version to use.  Examples:
   * package.json, .nvmrc, .node-version, .tool-versions.
   */
  'node-version-file'?: string;

  /**
   * Target architecture for Node to use. Examples: x86, x64. Will use
   * system architecture by default.
   */
  architecture?: string;

  /**
   * Set this option if you want the action to check for the latest
   * available version that satisfies the version spec.
   * @default false
   */
  'check-latest'?: boolean;

  /**
   * Optional registry to set up for auth. Will set the registry in a
   * project level .npmrc and .yarnrc file, and set up auth to read in from
   * env.NODE_AUTH_TOKEN.
   */
  'registry-url'?: string;

  /**
   * Optional scope for authenticating against scoped registries. Will fall
   * back to the repository owner when using the GitHub Packages registry
   * (https://npm.pkg.github.com/).
   */
  scope?: string;

  /**
   * Used to pull node distributions from node-versions. Since there's a
   * default, this is typically not supplied by the user. When running this
   * action on github.com, the default value is sufficient. When running on
   * GHES, you can pass a personal access token for github.com if you are
   * experiencing rate limiting.
   * @default "${{ github.server_url == 'https://github.com' && github.token || '' }}"
   */
  token?: string;

  /**
   * Used to specify a package manager for caching in the default
   * directory. Supported values: npm, yarn, pnpm.
   */
  cache?: string;

  /**
   * Used to specify the path to a dependency file: package-lock.json,
   * yarn.lock, etc. Supports wildcards or a list of file names for caching
   * multiple dependencies.
   */
  'cache-dependency-path'?: string;

  /**
   * Used to specify an alternative mirror to downlooad Node.js binaries
   * from
   */
  mirror?: string;

  /**
   * The token used as Authorization header when fetching from the mirror
   */
  'mirror-token'?: string;
}

/**
 * Inputs for codecov/codecov-action@v3
 * GitHub Action that uploads coverage reports for your repository to codecov.io
 */
export interface CodecovCodecovActionV3Inputs {
  /**
   * Repository upload token - get it from codecov.io. Required only for
   * private repositories
   */
  token?: string;

  /**
   * Path to coverage file to upload
   */
  file?: string;

  /**
   * Comma-separated list of files to upload
   */
  files?: string;

  /**
   * Directory to search for coverage reports.
   */
  directory?: string;

  /**
   * Flag upload to group coverage metrics (e.g. unittests | integration |
   * ui,chrome)
   */
  flags?: string;

  /**
   * Specify the path of a full Codecov report to re-upload
   */
  full_report?: string;

  /**
   * The commit SHA of the parent for which you are uploading coverage. If
   * not present, the parent will be determined using the API of your
   * repository provider.  When using the repository providers API, the
   * parent is determined via finding the closest ancestor to the commit.
   */
  commit_parent?: string;

  /**
   * Don't upload files to Codecov
   */
  dry_run?: string;

  /**
   * Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
   */
  env_vars?: string;

  /**
   * Specify whether or not CI build should fail if Codecov runs into an
   * error during upload
   */
  fail_ci_if_error?: string;

  /**
   * Comma-separated list, see the README for options and their usage.
   * Options include `network`, `fixes`, `search`.
   */
  functionalities?: string;

  /**
   * Run with gcov support
   */
  gcov?: string;

  /**
   * Extra arguments to pass to gcov
   */
  gcov_args?: string;

  /**
   * gcov executable to run. Defaults to gcov
   */
  gcov_executable?: string;

  /**
   * Paths to ignore during gcov gathering
   */
  gcov_ignore?: string;

  /**
   * Paths to include during gcov gathering
   */
  gcov_include?: string;

  /**
   * Move discovered coverage reports to the trash
   */
  move_coverage_to_trash?: string;

  /**
   * User defined upload name. Visible in Codecov UI
   */
  name?: string;

  /**
   * Specify a filter on the files listed in the network section of the
   * Codecov report. Useful for upload-specific path fixing
   */
  network_filter?: string;

  /**
   * Specify a prefix on files listed in the network section of the Codecov
   * report. Useful to help resolve path fixing
   */
  network_prefix?: string;

  /**
   * Override the assumed OS. Options are aarch64 | alpine | linux | macos
   * | windows.
   */
  os?: string;

  /**
   * Specify the branch name
   */
  override_branch?: string;

  /**
   * Specify the build number
   */
  override_build?: string;

  /**
   * Specify the commit SHA
   */
  override_commit?: string;

  /**
   * Specify the pull request number
   */
  override_pr?: string;

  /**
   * Specify the git tag
   */
  override_tag?: string;

  /**
   * Used when not in git/hg project to identify project root directory
   */
  root_dir?: string;

  /**
   * Specify the slug manually (Enterprise use)
   */
  slug?: string;

  /**
   * Run with swift coverage support
   */
  swift?: string;

  /**
   * Specify the swift project to speed up coverage conversion
   */
  swift_project?: string;

  /**
   * The upstream http proxy server to connect through
   */
  upstream_proxy?: string;

  /**
   * Change the upload host (Enterprise use)
   */
  url?: string;

  /**
   * Specify whether the Codecov output should be verbose
   */
  verbose?: string;

  /**
   * Specify which version of the Codecov Uploader should be used. Defaults
   * to `latest`
   */
  version?: string;

  /**
   * Directory in which to execute codecov.sh
   */
  'working-directory'?: string;

  /**
   * Run with xcode support
   */
  xcode?: string;

  /**
   * Specify the xcode archive path. Likely specified as the
   * -resultBundlePath and should end in .xcresult
   */
  xcode_archive_path?: string;

  /**
   * Add additional uploader args that may be missing in the Action
   */
  xtra_args?: string;
}

// Generic typed action builder - can be used for any action type
export interface Uses<TInputs = Record<string, any>> {
  with(inputs: TInputs): Uses<TInputs>;
  env(variables: Record<string, string | number | boolean>): Uses<TInputs>;
}

// Action mapping type - maps action strings to their input types
type ActionInputMap = {
  'actions/checkout@v4': ActionsCheckoutV4Inputs;
  'actions/setup-node@v4': ActionsSetupNodeV4Inputs;
  'codecov/codecov-action@v3': CodecovCodecovActionV3Inputs;
  // Add more actions here as they are discovered
};

// Module augmentation for type-safe .uses() callbacks
declare module 'flughafen' {
  interface StepBuilder {
    // Overloads for known GitHub Actions with typed callbacks
    uses<T extends keyof ActionInputMap>(
      action: T,
      callback: (uses: Uses<ActionInputMap[T]>) => Uses<ActionInputMap[T]>
    ): StepBuilder;

    // Generic string action with callback
    uses(
      action: string,
      callback: (uses: Uses<Record<string, any>>) => Uses<Record<string, any>>
    ): StepBuilder;

    // Direct string action (no callback)
    uses(action: string): StepBuilder;

    // Local action overloads (existing functionality)
    uses<TInputs = any, TOutputs = any>(action: LocalActionBuilder<TInputs, TOutputs>): StepBuilder;
    uses<TInputs = any, TOutputs = any>(
      action: LocalActionBuilder<TInputs, TOutputs>,
      callback: (uses: TypedActionConfigBuilder<TInputs>) => TypedActionConfigBuilder<TInputs>
    ): StepBuilder;
  }
}

declare module './src' {
  interface StepBuilder {
    // Overloads for known GitHub Actions with typed callbacks
    uses<T extends keyof ActionInputMap>(
      action: T,
      callback: (uses: Uses<ActionInputMap[T]>) => Uses<ActionInputMap[T]>
    ): StepBuilder;

    // Generic string action with callback
    uses(
      action: string,
      callback: (uses: Uses<Record<string, any>>) => Uses<Record<string, any>>
    ): StepBuilder;

    // Direct string action (no callback)
    uses(action: string): StepBuilder;

    // Local action overloads (existing functionality)
    uses<TInputs = any, TOutputs = any>(action: LocalActionBuilder<TInputs, TOutputs>): StepBuilder;
    uses<TInputs = any, TOutputs = any>(
      action: LocalActionBuilder<TInputs, TOutputs>,
      callback: (uses: TypedActionConfigBuilder<TInputs>) => TypedActionConfigBuilder<TInputs>
    ): StepBuilder;
  }
}

declare module './src/index' {
  interface StepBuilder {
    // Overloads for known GitHub Actions with typed callbacks
    uses<T extends keyof ActionInputMap>(
      action: T,
      callback: (uses: Uses<ActionInputMap[T]>) => Uses<ActionInputMap[T]>
    ): StepBuilder;

    // Generic string action with callback
    uses(
      action: string,
      callback: (uses: Uses<Record<string, any>>) => Uses<Record<string, any>>
    ): StepBuilder;

    // Direct string action (no callback)
    uses(action: string): StepBuilder;

    // Local action overloads (existing functionality)
    uses<TInputs = any, TOutputs = any>(action: LocalActionBuilder<TInputs, TOutputs>): StepBuilder;
    uses<TInputs = any, TOutputs = any>(
      action: LocalActionBuilder<TInputs, TOutputs>,
      callback: (uses: TypedActionConfigBuilder<TInputs>) => TypedActionConfigBuilder<TInputs>
    ): StepBuilder;
  }
}
