import { ModuleAugmentationGenerator } from "./module-augmentation-generator";
import type { GeneratedInterface } from "./type-generator-types";

/**
 * Generate complete .d.ts file content with interfaces and module augmentation
 */
export class TypeFileGenerator {
	private augmentationGenerator = new ModuleAugmentationGenerator();

	/**
	 * Generate a complete .d.ts file content with ambient module declarations
	 */
	generateTypeFile(interfaces: GeneratedInterface[]): string {
		const lines: string[] = [];

		// File header
		lines.push("// This file is auto-generated by Flughafen");
		lines.push("// Do not edit manually - regenerate using `flughafen generate-types`");
		lines.push("");
		lines.push("// Ambient module declaration - types are automatically available");
		lines.push("// No need to import this file explicitly");
		lines.push("");

		// Add imports for types used in module augmentation
		lines.push("import type { LocalActionBuilder, TypedActionConfigBuilder } from '@flughafen/core';");
		lines.push("");

		// Add all interfaces
		for (let i = 0; i < interfaces.length; i++) {
			const iface = interfaces[i];
			lines.push(iface.interfaceCode);

			// Add spacing between interfaces
			if (i < interfaces.length - 1) {
				lines.push("");
			}
		}

		// Add module augmentation directly in the same file
		if (interfaces.length > 0) {
			lines.push("");
			lines.push(this.augmentationGenerator.generateModuleAugmentation(interfaces));
		}

		return lines.join("\n");
	}

	/**
	 * Generate a complete .d.ts file with both external and local action types
	 */
	generateTypeFileWithLocalActions(
		externalInterfaces: GeneratedInterface[],
		localInterfaces: GeneratedInterface[]
	): string {
		const lines: string[] = [];

		// File header
		lines.push("// This file is auto-generated by Flughafen");
		lines.push("// Do not edit manually - regenerate using `flughafen generate-types`");
		lines.push("");
		lines.push("// Ambient module declaration - types are automatically available");
		lines.push("// No need to import this file explicitly");
		lines.push("");

		// Add imports for types used in module augmentation
		lines.push("import type { LocalActionBuilder, TypedActionConfigBuilder } from '@flughafen/core';");
		lines.push("");

		// Add common action interfaces at top level (always included)
		lines.push("// ===== Common GitHub Actions =====");
		lines.push("");
		lines.push(this.augmentationGenerator.generateCommonActionInterfaces());

		// Add external action interfaces
		if (externalInterfaces.length > 0) {
			lines.push("// ===== External GitHub Actions =====");
			lines.push("");
			for (const iface of externalInterfaces) {
				lines.push(iface.interfaceCode);
				lines.push("");
			}
		}

		// Add local action interfaces
		if (localInterfaces.length > 0) {
			lines.push("// ===== Local Actions =====");
			lines.push("");
			for (const iface of localInterfaces) {
				lines.push(iface.interfaceCode);
				lines.push("");
			}
		}

		// Add module augmentation (always include to provide common action interfaces)
		const allInterfaces = [...externalInterfaces, ...localInterfaces];
		lines.push(this.augmentationGenerator.generateModuleAugmentation(allInterfaces));

		return lines.join("\n");
	}
}
