export enum ErrorCode {
	// Builder/Configuration Errors
	BUILDER_CONFIGURATION_ERROR = "BUILDER_CONFIGURATION_ERROR",
	INVALID_JOB_CONFIGURATION = "INVALID_JOB_CONFIGURATION",
	INVALID_STEP_CONFIGURATION = "INVALID_STEP_CONFIGURATION",
	INVALID_ACTION_CONFIGURATION = "INVALID_ACTION_CONFIGURATION",
	MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

	// Compilation Errors
	TYPESCRIPT_COMPILATION_ERROR = "TYPESCRIPT_COMPILATION_ERROR",
	SYNTAX_ERROR = "SYNTAX_ERROR",
	MODULE_RESOLUTION_ERROR = "MODULE_RESOLUTION_ERROR",

	// File System Errors
	FILE_NOT_FOUND = "FILE_NOT_FOUND",
	FILE_READ_ERROR = "FILE_READ_ERROR",
	FILE_WRITE_ERROR = "FILE_WRITE_ERROR",
	DIRECTORY_CREATE_ERROR = "DIRECTORY_CREATE_ERROR",
	PERMISSION_ERROR = "PERMISSION_ERROR",

	// Processing Errors
	WORKFLOW_PROCESSING_ERROR = "WORKFLOW_PROCESSING_ERROR",
	INVALID_WORKFLOW_EXPORT = "INVALID_WORKFLOW_EXPORT",
	CIRCULAR_DEPENDENCY = "CIRCULAR_DEPENDENCY",

	// Network/Schema Errors
	SCHEMA_FETCH_ERROR = "SCHEMA_FETCH_ERROR",
	NETWORK_ERROR = "NETWORK_ERROR",
	SCHEMA_PARSE_ERROR = "SCHEMA_PARSE_ERROR",

	// Validation Errors
	WORKFLOW_VALIDATION_ERROR = "WORKFLOW_VALIDATION_ERROR",
	YAML_PARSE_ERROR = "YAML_PARSE_ERROR",
	SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR",

	// Sandbox Execution Errors
	SANDBOX_EXECUTION_ERROR = "SANDBOX_EXECUTION_ERROR",
	SANDBOX_TIMEOUT = "SANDBOX_TIMEOUT",
	SANDBOX_PERMISSION_ERROR = "SANDBOX_PERMISSION_ERROR",
}

export interface ErrorContext {
	[key: string]: unknown;
}
