#!/usr/bin/env node

import { compileFromFile } from "json-schema-to-typescript";
import fs from "node:fs";
import path from "node:path";

interface SchemaFile {
	filename: string;
	path: string;
	outputName: string;
}

async function generateTypes(): Promise<void> {
	try {
		console.log("🚀 Generating TypeScript types from JSON schemas...\n");

		const schemaDir = path.join(__dirname, "..", "schemas");
		const outputDir = path.join(__dirname, "..", "generated", "types");

		// Ensure the output directory exists
		if (!fs.existsSync(outputDir)) {
			fs.mkdirSync(outputDir, { recursive: true });
		}

		// Check if schema directory exists
		if (!fs.existsSync(schemaDir)) {
			console.error("❌ Schema directory not found:", schemaDir);
			console.log("💡 Run `npm run fetch-schemas` first to download schemas");
			process.exit(1);
		}

		// Find all .schema.json files
		const schemaFiles: SchemaFile[] = fs
			.readdirSync(schemaDir)
			.filter((file) => file.endsWith(".schema.json"))
			.map((file) => ({
				filename: file,
				path: path.join(schemaDir, file),
				outputName: file.replace(".schema.json", ".d.ts"),
			}));

		if (schemaFiles.length === 0) {
			console.log("⚠️  No schema files found in:", schemaDir);
			return;
		}

		console.log(`📋 Found ${schemaFiles.length} schema file(s):`);
		schemaFiles.forEach((file) => console.log(`   - ${file.filename}`));
		console.log("");

		// Process each schema file
		for (const schemaFile of schemaFiles) {
			console.log(`📝 Processing ${schemaFile.filename}...`);

			const outputPath = path.join(outputDir, schemaFile.outputName);

			// Generate schema name for banner comment
			const schemaName = schemaFile.filename
				.replace(".schema.json", "")
				.replace("-", " ")
				.split(" ")
				.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
				.join(" ");

			// Generate TypeScript types from the schema
			const ts = await compileFromFile(schemaFile.path, {
				bannerComment: `/**
 * Generated TypeScript definitions for ${schemaName} Schema
 * 
 * This file is auto-generated from the ${schemaFile.filename} schema file.
 * Do not edit this file directly. Instead, modify the schema file
 * and regenerate the types using: npm run generate-types
 * 
 * Generated on: ${new Date().toISOString()}
 */`,
				style: {
					bracketSpacing: true,
					printWidth: 120,
					semi: true,
					singleQuote: true,
					tabWidth: 2,
					trailingComma: "es5",
					useTabs: false,
				},
				additionalProperties: false,
				enableConstEnums: true,
				format: true,
				ignoreMinAndMaxItems: false,
				maxItems: 20,
				strictIndexSignatures: false,
				unknownAny: true,
				unreachableDefinitions: false,
			});

			// Write the generated types to file
			fs.writeFileSync(outputPath, ts);
			console.log(`✅ Types generated for ${schemaFile.filename} → ${schemaFile.outputName}`);
			console.log(`📦 File size: ${(fs.statSync(outputPath).size / 1024).toFixed(2)} KB`);
		}

		console.log(`\n🎉 Successfully generated types for ${schemaFiles.length} schema file(s)!`);
		console.log(`📁 Output directory: ${outputDir}`);
	} catch (error) {
		console.error("❌ Error generating types:", error);
		process.exit(1);
	}
}

generateTypes();
