#!/usr/bin/env node

const { compile, compileFromFile } = require('json-schema-to-typescript');
const fs = require('fs');
const path = require('path');

async function generateTypes() {
  try {
    console.log('Generating TypeScript types from schema.json...');
    
    const schemaPath = path.join(__dirname, '..', 'src', 'lib', 'schema.json');
    const outputPath = path.join(__dirname, '..', 'src', 'generated', 'github-actions.d.ts');
    
    // Ensure the output directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Generate TypeScript types from the schema
    const ts = await compileFromFile(schemaPath, {
      bannerComment: `/**
 * Generated TypeScript definitions for GitHub Actions Workflow Schema
 * 
 * This file is auto-generated from the GitHub Actions workflow schema.
 * Do not edit this file directly. Instead, modify the schema.json file
 * and regenerate the types using: npm run generate-types
 * 
 * Generated on: ${new Date().toISOString()}
 */`,
      style: {
        bracketSpacing: true,
        printWidth: 120,
        semi: true,
        singleQuote: true,
        tabWidth: 2,
        trailingComma: 'es5',
        useTabs: false,
      },
      additionalProperties: false,
      enableConstEnums: true,
      format: true,
      ignoreMinAndMaxItems: false,
      maxItems: 20,
      strictIndexSignatures: false,
      unknownAny: true,
      unreachableDefinitions: false,
    });
    
    // Write the generated types to file
    fs.writeFileSync(outputPath, ts);
    
    console.log(`✅ Types generated successfully at: ${outputPath}`);
    console.log(`📦 File size: ${(fs.statSync(outputPath).size / 1024).toFixed(2)} KB`);
    
  } catch (error) {
    console.error('❌ Error generating types:', error);
    process.exit(1);
  }
}

generateTypes();
