import { createWorkflow, expr } from "@flughafen/core";
import type { JobBuilder, StepBuilder, ActionBuilder } from "@flughafen/core";
/**
 * CI
 * ⚠️  WARNING: This file is generated by Flughafen
 * 
 * This workflow was generated from TypeScript source code.
 * Direct edits to this YAML file will be lost on the next build.
 * 
 * To make changes:
 * 1. Edit the source TypeScript workflow file
 * 2. Run: flughafen build
 * 
 * Learn more: https://github.com/your-org/flughafen
 * 
 */
export default createWorkflow()
	.name("CI")
	.env({
	  "NODE_ENV": "test",
	  "CI": "true"
	})
	.permissions({
	  "contents": "write",
	  "issues": "write",
	  "pull-requests": "write",
	  "id-token": "write"
	})
	.on("push", {
	  "branches": [
	    "main"
	  ]
	})
	.on("pull_request", {
	  "branches": [
	    "main"
	  ]
	})

	.job("setup", (job: JobBuilder) =>
		job
			.name("Setup and Build")
			.runsOn("ubuntu-latest")
			.outputs({
			  "cache-hit": "steps.cache.outputs.cache-hit"
			})

			.step((step: StepBuilder) =>
				step
					.name("Checkout repository")
					.uses("actions/checkout@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Install pnpm")
					.uses("pnpm/action-setup@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Setup Node.js")
					.uses("actions/setup-node@v4", (action: ActionBuilder) =>
						action
							.with({
							  nodeVersion: "22",
							  cache: "pnpm"
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Install dependencies")
					.run(`pnpm install --frozen-lockfile`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Build packages")
					.run(`pnpm build`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Cache workspace")
					.id("cache")
					.uses("actions/cache@v4", (action: ActionBuilder) =>
						action
							.with({
							  path: ".",
							  key: `workspace-${expr('runner.os')}-${expr('github.sha')}`
							})
					)
			)
	)

	.job("test", (job: JobBuilder) =>
		job
			.name("Test")
			.runsOn("ubuntu-latest")
			.needs(["setup"])

			.step((step: StepBuilder) =>
				step
					.name("Restore workspace")
					.uses("actions/cache@v4", (action: ActionBuilder) =>
						action
							.with({
							  path: ".",
							  key: `workspace-${expr('runner.os')}-${expr('github.sha')}`
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Run tests with coverage")
					.run(`pnpm test:coverage`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Run roundtrip tests")
					.run(`pnpm test:roundtrip`)
					.env({
					  GITHUB_TOKEN: expr('secrets.GITHUB_TOKEN')
					})
			)

			.step((step: StepBuilder) =>
				step
					.name("Run dogfood tests")
					.run(`pnpm test:dogfood`)
					.env({
					  GITHUB_TOKEN: expr('secrets.GITHUB_TOKEN')
					})
			)

			.step((step: StepBuilder) =>
				step
					.name("Upload coverage to Codecov")
					.uses("codecov/codecov-action@v4")
			)
	)

	.job("release", (job: JobBuilder) =>
		job
			.name("Release")
			.if("github.event_name == 'push' && github.ref == 'refs/heads/main'")
			.runsOn("ubuntu-latest")
			.needs(["setup", "test"])

			.step((step: StepBuilder) =>
				step
					.name("Checkout")
					.uses("actions/checkout@v4", (action: ActionBuilder) =>
						action
							.with({
							  fetchDepth: 0
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Restore workspace")
					.uses("actions/cache@v4", (action: ActionBuilder) =>
						action
							.with({
							  path: ".",
							  key: `workspace-${expr('runner.os')}-${expr('github.sha')}`
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Install pnpm")
					.uses("pnpm/action-setup@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Setup Node.js")
					.uses("actions/setup-node@v4", (action: ActionBuilder) =>
						action
							.with({
							  nodeVersion: "22",
							  cache: "pnpm",
							  registryUrl: "https://registry.npmjs.org"
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Upgrade npm for OIDC")
					.run(`npm install -g npm@latest`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Release")
					.run(`npx semantic-release`)
					.env({
					  GITHUB_TOKEN: expr('secrets.GITHUB_TOKEN')
					})
			)
	)

	.job("beta", (job: JobBuilder) =>
		job
			.name("Beta Release")
			.if("github.event_name == 'pull_request'")
			.runsOn("ubuntu-latest")
			.needs(["setup", "test"])

			.step((step: StepBuilder) =>
				step
					.name("Checkout")
					.uses("actions/checkout@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Restore workspace")
					.uses("actions/cache@v4", (action: ActionBuilder) =>
						action
							.with({
							  path: ".",
							  key: `workspace-${expr('runner.os')}-${expr('github.sha')}`
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Install pnpm")
					.uses("pnpm/action-setup@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Setup Node.js")
					.uses("actions/setup-node@v4", (action: ActionBuilder) =>
						action
							.with({
							  nodeVersion: "22",
							  cache: "pnpm",
							  registryUrl: "https://registry.npmjs.org"
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Upgrade npm for OIDC")
					.run(`npm install -g npm@latest`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Publish beta versions")
					.id("publish")
					.run(`SHORT_SHA=$(echo "$GITHUB_SHA" | cut -c1-7)
BRANCH_NAME="${expr('github.head_ref')}"
BRANCH_KEBAB=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')
BASE_VERSION=$(node -p "require('./packages/core/package.json').version")
PR_VERSION="$BASE_VERSION-pr.$BRANCH_KEBAB.$SHORT_SHA"

cd packages/core
npm pkg set version=$PR_VERSION
pnpm pack
npm publish flughafen-core-*.tgz --tag pr --access public --provenance

cd ../cli
npm pkg set version=$PR_VERSION
pnpm pack
npm publish flughafen-*.tgz --tag pr --access public --provenance

echo "version=$PR_VERSION" >> $GITHUB_OUTPUT`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Comment on PR")
					.uses("actions/github-script@v7", (action: ActionBuilder) =>
						action
							.with({
							  script: "const version = process.env.PR_VERSION;\n\ngithub.rest.issues.createComment({\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n  issue_number: context.issue.number,\n  body: '## 📦 PR Build Published\\n\\nInstall with:\\n```bash\\nnpm install @flughafen/core@' + version + '\\nnpm install flughafen@' + version + '\\n```'\n});"
							})
							.env({
							  PR_VERSION: expr('steps.publish.outputs.version')
							})
					)
			)
	)
;