import { createWorkflow, expr } from "@flughafen/core";
import type { JobBuilder, StepBuilder, ActionBuilder } from "@flughafen/core";
/**
 * Deploy Documentation
 * ⚠️  WARNING: This file is generated by Flughafen
 *
 * This workflow was generated from TypeScript source code.
 * Direct edits to this YAML file will be lost on the next build.
 *
 * To make changes:
 * 1. Edit the source TypeScript workflow file
 * 2. Run: flughafen build
 *
 * Learn more: https://github.com/your-org/flughafen
 *
 * Build core packages - needed for TypeDoc generation
 * Build VitePress static site
 */
export default createWorkflow()
	.name("Deploy Documentation")
	.permissions({
	  "contents": "read",
	  "pages": "write",
	  "id-token": "write"
	})
	.concurrency({
	  "group": "pages",
	  "cancel-in-progress": false
	})
	.on("push", {
	  "branches": [
	    "main"
	  ],
	  "paths": [
	    "docs/**",
	    "packages/flughafen/src/**"
	  ]
	})
	.on("workflow_dispatch")

	.job("build", (job: JobBuilder) =>
		job
			.runsOn("ubuntu-latest")

			.step((step: StepBuilder) =>
				step
					.name("Checkout repository")
					.uses("actions/checkout@v4", (action: ActionBuilder) =>
						action
							.with({
							  fetchDepth: 0
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Install pnpm")
					.uses("pnpm/action-setup@v4")
			)

			.step((step: StepBuilder) =>
				step
					.name("Setup Node.js")
					.uses("actions/setup-node@v4", (action: ActionBuilder) =>
						action
							.with({
							  nodeVersion: "20",
							  cache: "pnpm"
							})
					)
			)

			.step((step: StepBuilder) =>
				step
					.name("Install dependencies")
					.run(`pnpm install --frozen-lockfile`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Build packages")
					.run(`pnpm build`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Build documentation site")
					.run(`pnpm --filter docs build`)
			)

			.step((step: StepBuilder) =>
				step
					.name("Upload Pages artifact")
					.uses("actions/upload-pages-artifact@v3", (action: ActionBuilder) =>
						action
							.with({
							  path: "docs/dist"
							})
					)
			)
	)

	.job("deploy", (job: JobBuilder) =>
		job
			.runsOn("ubuntu-latest")
			.needs(["build"])
			.environment({"name":"github-pages","url":"${{ steps.deployment.outputs.page_url }}"})

			.step((step: StepBuilder) =>
				step
					.name("Deploy to GitHub Pages")
					.id("deployment")
					.uses("actions/deploy-pages@v4")
			)
	)
;